default_install_hook_types:
- pre-commit
- pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: ^\.idea
  - id: forbid-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: \.snap$
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.4.0
  hooks:
  - id: editorconfig-checker
    exclude_types:
    - ts
    - json
    - javascript
    - toml
    - yaml
    - xml
    - markdown
    - kotlin
    exclude: LICENSE|gradlew.bat|^\.idea
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    stages:
    - pre-commit
    - pre-push
    - pre-merge-commit
    types:
    - kotlin
    exclude: .*/gitversion/.*
    args:
    - --allow-past-years
    - --license-filepath
    - .license-header
    - --comment-style
    - '/*| *| */'
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.115.2
  hooks:
  - id: renovate-config-validator
    args:
    - --strict
- repo: https://github.com/andrewaylett/pre-commit-hooks
  rev: v0.7.0
  hooks:
  - id: init-hooks
- repo: local
  hooks:
  - id: ktlint
    stages:
    - pre-commit
    - pre-push
    name: KtLint
    language: system
    pass_filenames: false
    entry: ./gradlew :buildSrc:formatKotlin :formatKotlin
    types_or:
    - java
    - kotlin
  - id: check
    stages:
    - pre-commit
    - pre-push
    name: Gradle Check
    language: system
    pass_filenames: false
    entry: ./gradlew :buildSrc:check :check
    types_or:
    - java
    - kotlin
